/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlankAdminRouteImport } from './routes/blank-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NavigateStoreIdRouteImport } from './routes/navigate.$storeId'
import { Route as DestinationStoreIdRouteImport } from './routes/destination.$storeId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankAdminRoute = BlankAdminRouteImport.update({
  id: '/blank-admin',
  path: '/blank-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateStoreIdRoute = NavigateStoreIdRouteImport.update({
  id: '/navigate/$storeId',
  path: '/navigate/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationStoreIdRoute = DestinationStoreIdRouteImport.update({
  id: '/destination/$storeId',
  path: '/destination/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blank-admin': typeof BlankAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/destination/$storeId': typeof DestinationStoreIdRoute
  '/navigate/$storeId': typeof NavigateStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blank-admin': typeof BlankAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/destination/$storeId': typeof DestinationStoreIdRoute
  '/navigate/$storeId': typeof NavigateStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blank-admin': typeof BlankAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/destination/$storeId': typeof DestinationStoreIdRoute
  '/navigate/$storeId': typeof NavigateStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blank-admin'
    | '/sitemap.xml'
    | '/api/$'
    | '/category/$slug'
    | '/destination/$storeId'
    | '/navigate/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blank-admin'
    | '/sitemap.xml'
    | '/api/$'
    | '/category/$slug'
    | '/destination/$storeId'
    | '/navigate/$storeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blank-admin'
    | '/sitemap.xml'
    | '/api/$'
    | '/category/$slug'
    | '/destination/$storeId'
    | '/navigate/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlankAdminRoute: typeof BlankAdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DestinationStoreIdRoute: typeof DestinationStoreIdRoute
  NavigateStoreIdRoute: typeof NavigateStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank-admin': {
      id: '/blank-admin'
      path: '/blank-admin'
      fullPath: '/blank-admin'
      preLoaderRoute: typeof BlankAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate/$storeId': {
      id: '/navigate/$storeId'
      path: '/navigate/$storeId'
      fullPath: '/navigate/$storeId'
      preLoaderRoute: typeof NavigateStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$storeId': {
      id: '/destination/$storeId'
      path: '/destination/$storeId'
      fullPath: '/destination/$storeId'
      preLoaderRoute: typeof DestinationStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlankAdminRoute: BlankAdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  CategorySlugRoute: CategorySlugRoute,
  DestinationStoreIdRoute: DestinationStoreIdRoute,
  NavigateStoreIdRoute: NavigateStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
